version: "3"

services:
  app:
    build: .
    command: mix run --no-halt
    environment:
      - TELEGRAF_HOST=tempo_telegraf
      - TELEGRAF_PORT=8125
    networks:
      - tempo
  postgres:
    image: postgres:10.6-alpine
    container_name: tempo_postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=tempo
      - POSTGRES_PASSWORD=tempo
    networks:
      - tempo
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
  influx_db:
    image: influxdb:1.7.0
    container_name: tempo_influx_db
    ports:
      - 8086:8086
    networks:
      - tempo
    volumes:
      - "./data/influxdb:/var/lib/influxdb"
  telegraf:
    image: telegraf:1.8.3
    container_name: tempo_telegraf
    ports:
      - 8125:8125/udp
    networks:
      - tempo
    volumes:
      - "./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
  chronograf:
    image: chronograf:1.7.2
    container_name: tempo_chronograf
    ports:
      - 8888:8888
    networks:
      - tempo
    command: chronograf --influxdb-url=http://tempo_influx_db:8086
  kapacitor:
    image: kapacitor:1.5.1
    container_name: tempo_kapacitor
    ports:
      - 9092:9092
    networks:
      - tempo
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://tempo_influx_db:8086

networks:
  tempo:
    driver: bridge
